using System.Collections.Generic;
using System.Globalization;
using System.Threading;

namespace ClipyWin.Utilities;

public static class Loc
{
    public static string Culture { get; private set; } = "en";

    private static readonly Dictionary<string, Dictionary<string, string>> _dict = new()
    {
        ["en"] = new()
        {
            ["app.name"] = "Clipy",
            ["menu.preferences"] = "Preferences...",
            ["menu.editSnippets"] = "Edit Snippets...",
            ["menu.snippets"] = "Snippets",
            ["menu.clearHistory"] = "Clear History",
            ["menu.quit"] = "Quit Clipy",
            ["menu.noSnippets"] = "(no snippets)",
            ["menu.noHistory"] = "(history is empty)",
            ["confirm.clearHistoryTitle"] = "Clear history",
            ["confirm.clearHistoryBody"] = "Remove all clipboard items?",
            ["prefs.title"] = "Clipy Preferences",
            ["prefs.tab.general"] = "General",
            ["prefs.tab.menu"] = "Menu",
            ["prefs.tab.excluded"] = "Excluded Apps",
            ["prefs.tab.shortcuts"] = "Shortcuts",
            ["prefs.tab.updates"] = "Updates",
            ["prefs.close"] = "Close",
            ["prefs.language"] = "Language:",
            ["prefs.maxHistorySize"] = "Max history size:",
            ["prefs.reorder"] = "Move pasted clip to top",
            ["prefs.loginItem"] = "Launch Clipy at login",
            ["prefs.overwriteSame"] = "Overwrite same history entry",
            ["prefs.copySame"] = "Record duplicate copies",
            ["prefs.languageRestartHint"] = "Language changes apply immediately.",
            ["prefs.itemsShownInline"] = "Items shown inline:",
            ["prefs.itemsPerSubFolder"] = "Items per sub-folder:",
            ["prefs.maxTitleLength"] = "Max title length:",
            ["prefs.tooltipMaxLength"] = "Tooltip max length:",
            ["prefs.numberMenuItems"] = "Number menu items",
            ["prefs.startNumberFromZero"] = "Start numbering from 0",
            ["prefs.showTooltip"] = "Show tooltip on menu items",
            ["prefs.showClearHistoryItem"] = "Show 'Clear History' item in menu",
            ["prefs.confirmBeforeClear"] = "Confirm before clearing history",
            ["prefs.excludedHelp"] = "Clipboard content copied while one of these applications is focused will not be stored. Enter the process name (without .exe).",
            ["common.add"] = "Add",
            ["common.remove"] = "Remove",
            ["prefs.shortcutHelp"] = "Click a field, then press the desired key combo. Press Escape or Backspace to clear.",
            ["prefs.showHistoryMenu"] = "Show history menu:",
            ["prefs.showSnippetsMenu"] = "Show snippets menu:",
            ["prefs.updateHelp"] = "Configure a Velopack release feed URL to enable automatic updates. Leave empty to disable.",
            ["prefs.updateFeedUrl"] = "Update feed URL:",
            ["prefs.checkForUpdates"] = "Check for updates",
            ["prefs.downloadAndRestart"] = "Download & restart",
            ["prefs.updateChecking"] = "Checking...",
            ["prefs.updateDownloading"] = "Downloading...",
            ["prefs.updateRestarting"] = "Restarting...",
            ["prefs.updateFailed"] = "Update failed. See log for details.",
            ["hotkey.unassigned"] = "(unassigned)",
            ["error.loginItem"] = "Could not update login item: {0}",
            ["window.snippets"] = "Snippets",
            ["snippets.title"] = "Snippets",
            ["snippets.addFolder"] = "Add Folder",
            ["snippets.addSnippet"] = "Add Snippet",
            ["snippets.delete"] = "Delete",
            ["snippets.title.field"] = "Title:",
            ["snippets.content.field"] = "Content:",
            ["snippets.import"] = "Import XML...",
            ["snippets.export"] = "Export XML...",
            ["snippets.newFolder"] = "New Folder",
            ["snippets.newSnippet"] = "New Snippet",
            ["snippets.untitled"] = "(untitled)",
            ["snippets.empty"] = "(empty)",
            ["snippets.importTitle"] = "Import snippets",
            ["snippets.exportTitle"] = "Export snippets",
            ["snippets.exportFileName"] = "snippets.xml",
            ["snippets.importDone"] = "Import complete.",
            ["snippets.importFailed"] = "Import failed: {0}",
            ["snippets.exportDone"] = "Export complete.",
            ["snippets.exportFailed"] = "Export failed: {0}",
            ["snippets.deleteFolderConfirm"] = "Delete folder '{0}' and all its snippets?",
            ["menu.history"] = "History",
            ["menu.untitled"] = "(untitled)",
            ["menu.empty"] = "(empty)",
            ["menu.fallback.image"] = "(Image)",
            ["menu.fallback.files"] = "(Files)",
            ["menu.fallback.empty"] = "(Empty)",
        },
        ["tr"] = new()
        {
            ["app.name"] = "Clipy",
            ["menu.preferences"] = "Tercihler...",
            ["menu.editSnippets"] = "Snippet'leri Düzenle...",
            ["menu.snippets"] = "Snippet'ler",
            ["menu.clearHistory"] = "Geçmişi Temizle",
            ["menu.quit"] = "Clipy'yi Kapat",
            ["menu.noSnippets"] = "(snippet yok)",
            ["menu.noHistory"] = "(geçmiş boş)",
            ["confirm.clearHistoryTitle"] = "Geçmişi temizle",
            ["confirm.clearHistoryBody"] = "Tüm panoya kopyalananlar silinsin mi?",
            ["prefs.title"] = "Clipy Tercihleri",
            ["prefs.tab.general"] = "Genel",
            ["prefs.tab.menu"] = "Menü",
            ["prefs.tab.excluded"] = "Hariç Tutulan Uygulamalar",
            ["prefs.tab.shortcuts"] = "Kısayollar",
            ["prefs.tab.updates"] = "Güncellemeler",
            ["prefs.close"] = "Kapat",
            ["prefs.language"] = "Dil:",
            ["prefs.maxHistorySize"] = "Maks geçmiş boyutu:",
            ["prefs.reorder"] = "Yapıştırılanı en üste taşı",
            ["prefs.loginItem"] = "Oturum açınca Clipy başlat",
            ["prefs.overwriteSame"] = "Aynı geçmiş girdisini üzerine yaz",
            ["prefs.copySame"] = "Aynı kopyaları kaydet",
            ["prefs.languageRestartHint"] = "Dil değişiklikleri anında uygulanır.",
            ["prefs.itemsShownInline"] = "Doğrudan gösterilen öğe:",
            ["prefs.itemsPerSubFolder"] = "Alt klasör başına öğe:",
            ["prefs.maxTitleLength"] = "Maks başlık uzunluğu:",
            ["prefs.tooltipMaxLength"] = "İpucu maks uzunluğu:",
            ["prefs.numberMenuItems"] = "Menü öğelerini numaralandır",
            ["prefs.startNumberFromZero"] = "Numaralandırmaya 0'dan başla",
            ["prefs.showTooltip"] = "Menü öğelerinde ipucu göster",
            ["prefs.showClearHistoryItem"] = "Menüde 'Geçmişi Temizle' göster",
            ["prefs.confirmBeforeClear"] = "Temizlemeden önce onay iste",
            ["prefs.excludedHelp"] = "Bu uygulamalardan biri odaktayken kopyalanan pano içeriği kaydedilmez. İşlem adını (.exe olmadan) girin.",
            ["common.add"] = "Ekle",
            ["common.remove"] = "Kaldır",
            ["prefs.shortcutHelp"] = "Bir alana tıklayın, ardından tuş kombinasyonuna basın. Temizlemek için Escape veya Backspace.",
            ["prefs.showHistoryMenu"] = "Geçmiş menüsünü göster:",
            ["prefs.showSnippetsMenu"] = "Snippet menüsünü göster:",
            ["prefs.updateHelp"] = "Otomatik güncellemeleri açmak için Velopack sürüm akışı URL'si girin. Devre dışı bırakmak için boş bırakın.",
            ["prefs.updateFeedUrl"] = "Güncelleme akış URL'si:",
            ["prefs.checkForUpdates"] = "Güncellemeleri denetle",
            ["prefs.downloadAndRestart"] = "İndir ve yeniden başlat",
            ["prefs.updateChecking"] = "Denetleniyor...",
            ["prefs.updateDownloading"] = "İndiriliyor...",
            ["prefs.updateRestarting"] = "Yeniden başlatılıyor...",
            ["prefs.updateFailed"] = "Güncelleme başarısız. Ayrıntılar için günlüğe bakın.",
            ["hotkey.unassigned"] = "(atanmadı)",
            ["error.loginItem"] = "Girişte başlatma güncellenemedi: {0}",
            ["window.snippets"] = "Snippet'ler",
            ["snippets.title"] = "Snippet'ler",
            ["snippets.addFolder"] = "Klasör Ekle",
            ["snippets.addSnippet"] = "Snippet Ekle",
            ["snippets.delete"] = "Sil",
            ["snippets.title.field"] = "Başlık:",
            ["snippets.content.field"] = "İçerik:",
            ["snippets.import"] = "XML İçe Aktar...",
            ["snippets.export"] = "XML Dışa Aktar...",
            ["snippets.newFolder"] = "Yeni Klasör",
            ["snippets.newSnippet"] = "Yeni Snippet",
            ["snippets.untitled"] = "(başlıksız)",
            ["snippets.empty"] = "(boş)",
            ["snippets.importTitle"] = "Snippet içe aktar",
            ["snippets.exportTitle"] = "Snippet dışa aktar",
            ["snippets.exportFileName"] = "snippets.xml",
            ["snippets.importDone"] = "İçe aktarma tamamlandı.",
            ["snippets.importFailed"] = "İçe aktarma başarısız: {0}",
            ["snippets.exportDone"] = "Dışa aktarma tamamlandı.",
            ["snippets.exportFailed"] = "Dışa aktarma başarısız: {0}",
            ["snippets.deleteFolderConfirm"] = "'{0}' klasörü ve tüm snippet'leri silinsin mi?",
            ["menu.history"] = "Geçmiş",
            ["menu.untitled"] = "(başlıksız)",
            ["menu.empty"] = "(boş)",
            ["menu.fallback.image"] = "(Görsel)",
            ["menu.fallback.files"] = "(Dosyalar)",
            ["menu.fallback.empty"] = "(Boş)",
        },
        ["zh"] = new()
        {
            ["app.name"] = "Clipy",
            ["menu.preferences"] = "偏好设置...",
            ["menu.editSnippets"] = "编辑片段...",
            ["menu.snippets"] = "片段",
            ["menu.clearHistory"] = "清空历史",
            ["menu.quit"] = "退出 Clipy",
            ["menu.noSnippets"] = "(无片段)",
            ["menu.noHistory"] = "(历史为空)",
            ["confirm.clearHistoryTitle"] = "清空历史",
            ["confirm.clearHistoryBody"] = "要删除所有剪贴板项目吗？",
            ["prefs.title"] = "Clipy 偏好设置",
            ["prefs.tab.general"] = "常规",
            ["prefs.tab.menu"] = "菜单",
            ["prefs.tab.excluded"] = "排除应用",
            ["prefs.tab.shortcuts"] = "快捷键",
            ["prefs.tab.updates"] = "更新",
            ["prefs.close"] = "关闭",
            ["prefs.language"] = "语言:",
            ["prefs.maxHistorySize"] = "最大历史条数:",
            ["prefs.reorder"] = "粘贴后将条目移到顶部",
            ["prefs.loginItem"] = "登录时启动 Clipy",
            ["prefs.overwriteSame"] = "覆盖相同历史记录",
            ["prefs.copySame"] = "记录重复复制",
            ["prefs.languageRestartHint"] = "语言切换会立即生效。",
            ["prefs.itemsShownInline"] = "直接显示条目数:",
            ["prefs.itemsPerSubFolder"] = "每个子文件夹条目数:",
            ["prefs.maxTitleLength"] = "标题最大长度:",
            ["prefs.tooltipMaxLength"] = "提示最大长度:",
            ["prefs.numberMenuItems"] = "菜单条目编号",
            ["prefs.startNumberFromZero"] = "从 0 开始编号",
            ["prefs.showTooltip"] = "在菜单条目显示提示",
            ["prefs.showClearHistoryItem"] = "菜单中显示“清空历史”",
            ["prefs.confirmBeforeClear"] = "清空前确认",
            ["prefs.excludedHelp"] = "当以下应用处于前台时复制的内容不会写入历史。请输入进程名（不含 .exe）。",
            ["common.add"] = "添加",
            ["common.remove"] = "移除",
            ["prefs.shortcutHelp"] = "点击输入框后按下快捷键组合。按 Escape 或 Backspace 可清除。",
            ["prefs.showHistoryMenu"] = "显示历史菜单:",
            ["prefs.showSnippetsMenu"] = "显示片段菜单:",
            ["prefs.updateHelp"] = "配置 Velopack 发布源 URL 以启用自动更新。留空则禁用。",
            ["prefs.updateFeedUrl"] = "更新源 URL:",
            ["prefs.checkForUpdates"] = "检查更新",
            ["prefs.downloadAndRestart"] = "下载并重启",
            ["prefs.updateChecking"] = "检查中...",
            ["prefs.updateDownloading"] = "下载中...",
            ["prefs.updateRestarting"] = "正在重启...",
            ["prefs.updateFailed"] = "更新失败，请查看日志。",
            ["hotkey.unassigned"] = "(未分配)",
            ["error.loginItem"] = "无法更新开机启动设置: {0}",
            ["window.snippets"] = "片段",
            ["snippets.title"] = "片段",
            ["snippets.addFolder"] = "添加文件夹",
            ["snippets.addSnippet"] = "添加片段",
            ["snippets.delete"] = "删除",
            ["snippets.title.field"] = "标题:",
            ["snippets.content.field"] = "内容:",
            ["snippets.import"] = "导入 XML...",
            ["snippets.export"] = "导出 XML...",
            ["snippets.newFolder"] = "新建文件夹",
            ["snippets.newSnippet"] = "新建片段",
            ["snippets.untitled"] = "(未命名)",
            ["snippets.empty"] = "(空)",
            ["snippets.importTitle"] = "导入片段",
            ["snippets.exportTitle"] = "导出片段",
            ["snippets.exportFileName"] = "snippets.xml",
            ["snippets.importDone"] = "导入完成。",
            ["snippets.importFailed"] = "导入失败: {0}",
            ["snippets.exportDone"] = "导出完成。",
            ["snippets.exportFailed"] = "导出失败: {0}",
            ["snippets.deleteFolderConfirm"] = "要删除文件夹“{0}”及其所有片段吗？",
            ["menu.history"] = "历史",
            ["menu.untitled"] = "(未命名)",
            ["menu.empty"] = "(空)",
            ["menu.fallback.image"] = "(图片)",
            ["menu.fallback.files"] = "(文件)",
            ["menu.fallback.empty"] = "(空)",
        },
    };

    public static void Set(string culture)
    {
        if (string.IsNullOrWhiteSpace(culture)) culture = "en";
        culture = culture.ToLowerInvariant();
        if (!_dict.ContainsKey(culture)) culture = "en";
        Culture = culture;
        try
        {
            var ci = CultureInfo.GetCultureInfo(culture switch
            {
                "tr" => "tr-TR",
                "zh" => "zh-CN",
                _ => "en-US"
            });
            Thread.CurrentThread.CurrentUICulture = ci;
            Thread.CurrentThread.CurrentCulture = ci;
            CultureInfo.DefaultThreadCurrentUICulture = ci;
            CultureInfo.DefaultThreadCurrentCulture = ci;
        }
        catch { }
    }

    public static string T(string key)
    {
        if (_dict.TryGetValue(Culture, out var d) && d.TryGetValue(key, out var v)) return v;
        return _dict["en"].TryGetValue(key, out var en) ? en : key;
    }

    public static IReadOnlyList<(string Code, string Name)> SupportedLanguages { get; } = new[]
    {
        ("en", "English"),
        ("tr", "Türkçe"),
        ("zh", "简体中文"),
    };
}
